public class Dog{
    string name;
    boolean ismale;
    int num of puppies;
    string list of puppie[]=new string[8];


    public void setName(string name){
        Name = name;
    }

    public string showName(){
        return Name;
    }
     public void bark (){
        system.out.println(x:"ARF ARF");
     }

     public int show_numofpuppies(){
        int count = 0;
        for(int i = 0; i < listofpuppies.lenght; i++){
            system.out.print(listofpuppies[]);
        
        }
     }
     }
     